### ISSUE TITLE
Traceback - Error Running

### ISSUE THREAD

**Issue by drkui** [Wingman4l7/relisterine#1]
I pip-installed selenium and colorama, put in my Craigslist creds in the relisterine_config.ini file, and then ran `python relisterine.py`. 

This is what I got:
```
Traceback (most recent call last):
  File "relisterine.py", line 133, in <module>
    main()
  File "relisterine.py", line 105, in main
    chromedriver = webdriver.Chrome('/Python27/selenium/webdriver/chromedriver', chrome_options=opts)
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

**Comment by Wingman4l7** [comment]
I forgot to mention in the README that you will also need to pull down the chromedriver binary.  That's probably what you're missing.  You may then still get the `WedDriverException` that it cannot be found, because I hardcoded its path (see line # 105).  You can simply edit this path to point to wherever you installed chromedriver, and it should work!
